function migrateV1LocalState(workspaceLocal) {
  const oldState = readLocal(V1_LOCAL_KEY, null);
  const financeState = ensureWorkspaceProjectState(workspaceLocal, FINANCE_PROJECT_ID);
  if (oldState && !workspaceLocal.migrations?.v1LocalImported) {
    workspaceLocal.projectStates[FINANCE_PROJECT_ID] = mergeProjectLocalStates(financeState, oldState, workspaceLocal, 'v1-localStorage');
    workspaceLocal.migrations = { ...asObject(workspaceLocal.migrations), v1LocalImported: nowIso() };
  }
  workspaceLocal.projectStates[FINANCE_PROJECT_ID] = migrateExistingLegacyBrowserState(workspaceLocal.projectStates[FINANCE_PROJECT_ID]);
  return workspaceLocal;
}
function ensureWorkspaceProjectState(workspaceLocal,projectId){if(!workspaceLocal.projectStates[projectId])workspaceLocal.projectStates[projectId]=baseProjectLocalState();workspaceLocal.projectStates[projectId]=normalizeProjectLocalState(workspaceLocal.projectStates[projectId]);return workspaceLocal.projectStates[projectId]}
function syncV1Compatibility(){const financeState=WORKSPACE_LOCAL?.projectStates?.[FINANCE_PROJECT_ID];if(!financeState)return;writeLocal(V1_LOCAL_KEY,financeState);const todoState=readLocal(LEGACY_TODO_KEY,{});for(const[id,value]of Object.entries(financeState.batchTaskState))todoState[id]=value?.status==='done';writeLocal(LEGACY_TODO_KEY,todoState);const testState=readLocal(LEGACY_TEST_KEY,{});for(const[id,result]of Object.entries(financeState.testResults)){testState[id]={...asObject(testState[id]),done:result.status==='passed',status:result.status||'untested',note:result.note||'',device:result.device||'',browser:result.browser||'',environment:result.environment||'',actualResult:result.actualResult||'',lastTestedAt:result.lastTestedAt||''}}writeLocal(LEGACY_TEST_KEY,testState);localStorage.setItem(LEGACY_NOTE_KEY,financeState.legacyGeneralNotes||'')}
function saveWorkspace({render=false}={}){WORKSPACE_LOCAL.updatedAt=nowIso();writeLocal(WORKSPACE_LOCAL_KEY,WORKSPACE_LOCAL);syncV1Compatibility();markSaved();if(render)renderApp()}
function saveLocal({render=false,timeline=null}={}){if(!ACTIVE_PROJECT_ID||!LOCAL)return saveWorkspace({render});LOCAL.updatedAt=nowIso();if(timeline)addTimeline(timeline,false);WORKSPACE_LOCAL.projectStates[ACTIVE_PROJECT_ID]=LOCAL;saveWorkspace({render})}
function addTimeline(entry,persist=true){if(!LOCAL)return;LOCAL.timeline.unshift({id:uniqueId('local-event'),date:nowIso(),type:'local',...entry});LOCAL.timeline=LOCAL.timeline.slice(0,250);if(persist)saveLocal()}
async function fetchJson(path,cacheKey,{timeoutMs=6500}={}){const controller=typeof AbortController!=='undefined'?new AbortController():null;const timeout=controller?setTimeout(()=>controller.abort(),timeoutMs):null;try{const response=await fetch(`${path}?t=${Date.now()}`,{cache:'no-store',signal:controller?.signal});if(!response.ok)throw new Error(`${path}: HTTP ${response.status}`);const contentType=response.headers.get('content-type')||'';if(!contentType.includes('json'))throw new Error(`${path}: Unerwarteter Inhaltstyp ${contentType||'unbekannt'}`);const data=await response.json();localStorage.setItem(cacheKey,JSON.stringify(data));return{data,source:'network'}}catch(error){const reason=error?.name==='AbortError'?`${path}: Zeitüberschreitung nach ${Math.round(timeoutMs/1000)} Sekunden`:error?.message||String(error);const cached=parseJson(localStorage.getItem(cacheKey)||'',null);if(cached)return{data:cached,source:'cache',warning:reason};return{data:null,source:'missing',warning:reason}}finally{if(timeout)clearTimeout(timeout)}}
function groupBy(items,key){return asArray(items).reduce((groups,item)=>{const value=item[key]||'Ohne Gruppe';(groups[value]||=[]).push(item);return groups},{})}
function adaptLegacyData(legacy){if(!legacy||!Array.isArray(legacy.todos)||!Array.isArray(legacy.tests))return{batches:[],tests:[]};const batches=Object.entries(groupBy(legacy.todos,'batch')).map(([batchId,tasks])=>({id:batchId,title:tasks[0]?.batchTitle||batchId,description:'Historischer Batch aus todo-data.json. IDs und lokale Zustände bleiben unverändert.',status:'Archiviert',priority:'P1',phaseId:'phase-finanztracker-stabilization',time:tasks[0]?.time||'',source:'legacy-todo-data',tasks:tasks.map(task=>({id:task.id,title:task.text,tag:task.tag,legacy:true}))}));const taskToBatch={};for(const batch of batches)for(const task of batch.tasks)taskToBatch[task.id]=batch.id;const tests=legacy.tests.map(test=>({id:test.id,suite:test.suite,suiteTitle:test.suiteTitle,title:test.title,description:'',relatedTaskIds:asArray(test.relatedTodos),relatedBatchIds:[...new Set(asArray(test.relatedTodos).map(id=>taskToBatch[id]).filter(Boolean))],when:test.when||'',steps:asArray(test.steps),expected:asArray(test.expected),source:'legacy-todo-data'}));return{batches,tests}}
function mergeById(primary,secondary){const map=new Map();for(const item of[...asArray(primary),...asArray(secondary)]){if(!item?.id||map.has(item.id))continue;map.set(item.id,item)}return[...map.values()]}
function normalizeProject(project){const source=asObject(project);return{...source,legacyProjectIds:asArray(source.legacyProjectIds),goals:asObject(source.goals),phases:asArray(source.phases),gates:asArray(source.gates),batches:asArray(source.batches),mikaTasks:asArray(source.mikaTasks),tests:asArray(source.tests),bugs:asArray(source.bugs),ideas:asArray(source.ideas),questions:asArray(source.questions),decisions:asArray(source.decisions),aiModels:asArray(source.aiModels),files:asArray(source.files),backups:asArray(source.backups),github:asObject(source.github),timeline:asArray(source.timeline),risks:asArray(source.risks),notes:asArray(source.notes),workflowState:{currentLifecyclePhaseId:source.workflowState?.currentLifecyclePhaseId||source.workflowPhaseId||'',gateStatuses:asObject(source.workflowState?.gateStatuses),repositoryChecklist:asArray(source.workflowState?.repositoryChecklist),workflowFiles:asArray(source.workflowState?.workflowFiles),routingOverrides:asArray(source.workflowState?.routingOverrides)}}}
function migrateSingleProjectV1(raw){const source=asObject(raw),projectInfo=asObject(source.project);const project=normalizeProject({id:FINANCE_PROJECT_ID,legacyProjectIds:[projectInfo.id||'finanztracker-tool'],name:projectInfo.name||'Buchhaltungs Tool / Finanz Tracker',shortName:'Finanztracker',description:projectInfo.description||'',status:'active',statusLabel:projectInfo.status||'Active',phase:projectInfo.mode||'',currentPhaseId:projectInfo.currentPhaseId||'',progress:0,lastUpdated:source.updatedAt||today(),nextAction:asArray(projectInfo.nextSteps)[0]||'',goals:{goal:projectInfo.goal||'',problem:projectInfo.problem||'',targetGroup:projectInfo.targetGroup||'',successCriteria:asArray(projectInfo.successCriteria),nonGoals:asArray(projectInfo.nonGoals),constraints:asArray(projectInfo.constraints)},phases:source.phases,batches:source.batches,mikaTasks:source.mikaTasks,tests:source.tests,bugs:source.bugs,ideas:source.ideas,questions:source.questions,decisions:source.decisions,aiModels:[],files:source.files,backups:source.backups,github:source.github,timeline:source.timeline,risks:source.risks,notes:source.notes,legacyMasterchat:source.masterchat,legacySubchats:source.subchats,legacyAiBatches:source.aiBatches});return{schema:WORKSPACE_SCHEMA,updatedAt:source.updatedAt||today(),global:{toolName:'KI-Projektmanagement',privacyMode:'private_repo_recommended'},workflowTemplates:{roles:[],lifecyclePhases:[],gates:[],repositoryChecklist:[],workflowFiles:[],modelRoutingRules:[]},projects:[project],legacySources:{v1ProjectDataSchema:V1_PROJECT_SCHEMA,financeProjectId:FINANCE_PROJECT_ID}}}
function normalizeWorkspaceData(raw,legacy,importedProjects=[]){let source;if(raw?.schema===WORKSPACE_SCHEMA&&Array.isArray(raw.projects))source=raw;else if(raw?.schemaVersion===V1_PROJECT_SCHEMA&&raw.project)source=migrateSingleProjectV1(raw);else source={schema:WORKSPACE_SCHEMA,updatedAt:today(),global:{toolName:'KI-Projektmanagement'},workflowTemplates:{},projects:[],legacySources:{}};const workspace={schema:source.schema||WORKSPACE_SCHEMA,updatedAt:source.updatedAt||today(),global:asObject(source.global),workflowTemplates:{roles:asArray(source.workflowTemplates?.roles),lifecyclePhases:asArray(source.workflowTemplates?.lifecyclePhases),gates:asArray(source.workflowTemplates?.gates),repositoryChecklist:asArray(source.workflowTemplates?.repositoryChecklist),workflowFiles:asArray(source.workflowTemplates?.workflowFiles),modelRoutingRules:asArray(source.workflowTemplates?.modelRoutingRules)},projects:asArray(source.projects).map(normalizeProject),legacySources:asObject(source.legacySources),sourceInfo:{workspaceData:raw?'project-data.json':'nicht verfügbar',legacyData:legacy?'todo-data.json':'nicht verfügbar'}};for(const imported of asArray(importedProjects)){if(!imported?.id||workspace.projects.some(project=>project.id===imported.id))continue;workspace.projects.push(normalizeProject({...imported,source:'local-import'}))}const finance=workspace.projects.find(project=>project.id===FINANCE_PROJECT_ID||project.legacyProjectIds.includes('finanztracker-tool'));if(finance){finance.id=FINANCE_PROJECT_ID;const adapted=adaptLegacyData(legacy);finance.batches=mergeById(finance.batches,adapted.batches);finance.tests=mergeById(finance.tests,adapted.tests)}return workspace}
