function mergeArrayPreservingConflicts(existing, imported, prefix, workspaceLocal = WORKSPACE_LOCAL) {
  const result = [...asArray(existing)];
  const byId = new Map(result.map(item => [item.id,item]));
  for (const item of asArray(imported)) {
    if (!item?.id) { result.push({...item,id:uniqueId(prefix)}); continue; }
    const found = byId.get(item.id);
    if (!found) { result.push(item); byId.set(item.id,item); }
    else if (JSON.stringify(found) !== JSON.stringify(item)) {
      const conflict={...item,id:`${item.id}-import-${Math.random().toString(36).slice(2,7)}`,importedFromId:item.id};
      result.push(conflict);
      workspaceLocal?.conflictCopies?.push({id:uniqueId('conflict'),createdAt:nowIso(),originalId:item.id,conflictId:conflict.id,type:prefix});
    }
  }
  return result;
}
function mergeTestResults(existing,imported){const result={...asObject(existing)};for(const[id,raw]of Object.entries(asObject(imported))){const incoming=asObject(raw);if(!result[id]){result[id]=incoming;continue}const current=asObject(result[id]);result[id]={...incoming,...current,status:current.status&&current.status!=='untested'?current.status:incoming.status||(incoming.done?'passed':'untested'),note:mergeText(current.note,incoming.note,'importierte Testnotiz'),actualResult:mergeText(current.actualResult,incoming.actualResult,'importiertes Ergebnis'),updatedAt:nowIso()}}return result}
function mergeProjectLocalStates(existingRaw,importedRaw,workspaceLocal=WORKSPACE_LOCAL,source='import'){const existing=normalizeProjectLocalState(existingRaw),incoming=normalizeProjectLocalState(importedRaw),taskState={...incoming.batchTaskState,...existing.batchTaskState};for(const id of new Set([...Object.keys(incoming.batchTaskState),...Object.keys(existing.batchTaskState)])){if(incoming.batchTaskState[id]?.status==='done'||existing.batchTaskState[id]?.status==='done')taskState[id]={...incoming.batchTaskState[id],...existing.batchTaskState[id],status:'done'}}return normalizeProjectLocalState({...incoming,...existing,batchTaskState:taskState,testResults:mergeTestResults(existing.testResults,incoming.testResults),mikaTasks:mergeArrayPreservingConflicts(existing.mikaTasks,incoming.mikaTasks,'mika-task',workspaceLocal),bugs:mergeArrayPreservingConflicts(existing.bugs,incoming.bugs,'bug-local',workspaceLocal),ideas:mergeArrayPreservingConflicts(existing.ideas,incoming.ideas,'idea-local',workspaceLocal),questions:mergeArrayPreservingConflicts(existing.questions,incoming.questions,'question-local',workspaceLocal),decisions:mergeArrayPreservingConflicts(existing.decisions,incoming.decisions,'decision-local',workspaceLocal),quickNotes:mergeArrayPreservingConflicts(existing.quickNotes,incoming.quickNotes,'note-local',workspaceLocal),backups:mergeArrayPreservingConflicts(existing.backups,incoming.backups,'backup-local',workspaceLocal),chatOverrides:{...incoming.chatOverrides,...existing.chatOverrides},gateOverrides:{...incoming.gateOverrides,...existing.gateOverrides},timeline:mergeArrayPreservingConflicts(existing.timeline,incoming.timeline,'local-event',workspaceLocal),legacyGeneralNotes:mergeText(existing.legacyGeneralNotes,incoming.legacyGeneralNotes,`importierte allgemeine Notizen (${source})`),importHistory:[...existing.importHistory,...incoming.importHistory],importedProjectSnapshots:[...existing.importedProjectSnapshots,...incoming.importedProjectSnapshots],entityOverrides:{bugs:{...incoming.entityOverrides.bugs,...existing.entityOverrides.bugs},ideas:{...incoming.entityOverrides.ideas,...existing.entityOverrides.ideas},questions:{...incoming.entityOverrides.questions,...existing.entityOverrides.questions},decisions:{...incoming.entityOverrides.decisions,...existing.entityOverrides.decisions}}})}
function renderProjectNavigation(){const sidebar=$('#desktopProjectNav'),drawer=$('#mobileProjectNav');if(!DATA){if(sidebar)sidebar.innerHTML='';if(drawer)drawer.innerHTML='';return}const active=LOCAL.ui.activeView;const markup=PROJECT_NAV_GROUPS.map(group=>{const groupActive=group.items.some(item=>item[0]===active);return`<details class="nav-group" ${groupActive?'open':''} data-nav-group="${esc(group.id)}"><summary><span>${esc(group.icon)}</span>${esc(group.label)}</summary><div>${group.items.map(([id,icon,label])=>`<button type="button" data-project-view="${id}" class="${active===id?'active':''}"><span class="nav-icon">${esc(icon)}</span><span>${esc(label)}</span>${navigationCount(id)?`<span class="nav-count">${navigationCount(id)}</span>`:''}</button>`).join('')}</div></details>`}).join('');if(sidebar)sidebar.innerHTML=markup;if(drawer)drawer.innerHTML=markup;$$('[data-project-view]').forEach(button=>button.addEventListener('click',()=>navigateProject(button.dataset.projectView)));$$('.project-bottom-nav [data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===active));$('#projectMoreButton')?.classList.toggle('active',!PRIMARY_PROJECT_VIEWS.includes(active))}
function navigationCount(view){if(!DATA||!LOCAL)return'';const stats=projectStats(DATA);if(view==='work')return stats.openMika||'';if(view==='quality')return(stats.openBugs+(DATA.tests.length-stats.testsDone))||'';if(view==='ai')return stats.overdueBackups||'';if(view==='knowledge')return(stats.openQuestions+stats.activeDecisions)||'';return''}
