async function handleScreenshotInput(event){const testId=event.target.dataset.screenshotInput;for(const file of event.target.files){if(!file.type.startsWith('image/'))continue;const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});await dbPut({id:`${ACTIVE_PROJECT_ID}-${testId}-${Date.now()}-${Math.random().toString(36).slice(2)}`,projectId:ACTIVE_PROJECT_ID,testId,name:file.name,type:file.type,size:file.size,createdAt:nowIso(),dataUrl})}event.target.value='';addTimeline({title:`Screenshot zu Test ${testId} angehängt`,description:'Lokaler Anhang in IndexedDB gespeichert.',type:'test',targetView:'quality'},false);saveLocal();renderAllScreenshotGrids();showToast('Screenshot lokal gespeichert.','success')}
async function renderAllScreenshotGrids(){if(!DATA)return;let screenshots=[];try{screenshots=await dbAllForProject(DATA.id)}catch{return}$$('[data-screenshot-grid]').forEach(grid=>{const testId=grid.dataset.screenshotGrid,items=screenshots.filter(item=>item.testId===testId);grid.innerHTML=items.map(item=>`<div class="screenshot"><img src="${item.dataUrl}" alt="Lokaler Testscreenshot"><div class="screenshot-name">${esc(item.name)}</div><button class="button button-small button-ghost" data-delete-shot="${esc(item.id)}">Entfernen</button></div>`).join('')});$$('[data-delete-shot]').forEach(button=>button.addEventListener('click',async()=>{if(!confirm('Diesen lokalen Screenshot entfernen?'))return;await dbDelete(button.dataset.deleteShot);renderAllScreenshotGrids()}))}
async function mergeScreenshots(imported,fallbackProjectId=FINANCE_PROJECT_ID){const existing=await dbAll(),ids=new Set(existing.map(item=>item.id));let added=0,conflicts=0;for(const raw of asArray(imported)){if(!raw?.dataUrl)continue;const item={...raw,projectId:raw.projectId||fallbackProjectId};if(!item.id||ids.has(item.id)){item.id=`${item.projectId}-${item.testId||'attachment'}-import-${Date.now()}-${Math.random().toString(36).slice(2)}`;conflicts++}ids.add(item.id);await dbPut(item);added++}return{added,conflicts}}
function exportLegacyTodoState(projectState){const state=readLocal(LEGACY_TODO_KEY,{});for(const[id,value]of Object.entries(projectState.batchTaskState))state[id]=value?.status==='done';return state}
function exportLegacyTestState(projectState){const state=readLocal(LEGACY_TEST_KEY,{});for(const[id,result]of Object.entries(projectState.testResults))state[id]={...asObject(state[id]),done:result.status==='passed',...result};return state}
function downloadJson(payload,fileName){const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=fileName;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
function buildGlobalBackupPayload(screenshots=[]){const financeState=ensureProjectLocal(FINANCE_PROJECT_ID);return{schema:BACKUP_SCHEMA,scope:'global',exportedAt:nowIso(),workspaceDataVersion:WORKSPACE.updatedAt,workspaceDataSnapshot:RAW_WORKSPACE,localWorkspaceState:WORKSPACE_LOCAL,screenshots:asArray(screenshots),legacyCompatibility:{todoState:exportLegacyTodoState(financeState),testState:exportLegacyTestState(financeState),generalNotes:financeState.legacyGeneralNotes||''}}}
function buildProjectBackupPayload(project=DATA,projectState=LOCAL,screenshots=[]){if(!project||!projectState)throw new Error('Kein aktives Projekt für Projekt-Export.');const payload={schema:BACKUP_SCHEMA,scope:'project',exportedAt:nowIso(),projectId:project.id,projectDataSnapshot:project,projectLocalState:projectState,screenshots:asArray(screenshots).filter(item=>screenshotProjectId(item)===project.id)};if(project.id===FINANCE_PROJECT_ID)payload.legacyCompatibility={todoState:exportLegacyTodoState(projectState),testState:exportLegacyTestState(projectState),generalNotes:projectState.legacyGeneralNotes||''};return payload}
async function exportGlobalBackup(){try{for(const project of WORKSPACE.projects)refreshUnmappedLegacy(project.id);saveWorkspace();const screenshots=await dbAll(),payload=buildGlobalBackupPayload(screenshots);downloadJson(payload,`mika-ai-project-workspace-backup-${today()}.json`);WORKSPACE_LOCAL.importHistory.unshift({id:uniqueId('export'),importedAt:nowIso(),fileName:'global export',schema:BACKUP_SCHEMA,summary:`Global export with ${WORKSPACE.projects.length} projects and ${screenshots.length} screenshots.`});saveWorkspace();showToast('Globales Workspace-Backup exportiert.','success')}catch(error){showToast(`Globaler Export fehlgeschlagen: ${error.message}`,'danger')}}
async function exportProjectBackup(){if(!DATA||!LOCAL)return;try{refreshUnmappedLegacy(DATA.id);saveLocal();const screenshots=await dbAllForProject(DATA.id),payload=buildProjectBackupPayload(DATA,LOCAL,screenshots);downloadJson(payload,`${DATA.id}-backup-${today()}.json`);addTimeline({title:'Projekt-Backup exportiert',description:`${screenshots.length} projektbezogene Screenshots eingeschlossen.`,type:'backup',targetView:'files'},false);saveLocal();showToast('Projekt-Backup exportiert.','success')}catch(error){showToast(`Projekt-Export fehlgeschlagen: ${error.message}`,'danger')}}
function localStateFromLegacyBackup(payload){const state=baseProjectLocalState(),todo={...asObject(payload.done),...asObject(payload.todoState)};for(const[rawId,value]of Object.entries(todo)){const id=ID_ALIASES[rawId]||rawId;state.batchTaskState[id]={status:value===true||value?.done===true?'done':'open',updatedAt:nowIso(),source:'legacy-import'}}for(const[id,value]of Object.entries(asObject(payload.testState))){const raw=asObject(value);state.testResults[id]={status:raw.status||(raw.done?'passed':'untested'),device:raw.device||'',browser:raw.browser||'',environment:raw.environment||'',actualResult:raw.actualResult||'',note:raw.note||'',lastTestedAt:raw.lastTestedAt||'',updatedAt:nowIso()}}state.legacyGeneralNotes=typeof payload.generalNotes==='string'?payload.generalNotes:typeof payload.notes==='string'?payload.notes:'';return state}
function resolveProjectId(rawProjectId){if(!rawProjectId||rawProjectId==='finanztracker-tool')return FINANCE_PROJECT_ID;const direct=projectById(rawProjectId);if(direct)return direct.id;const alias=WORKSPACE.projects.find(project=>project.legacyProjectIds.includes(rawProjectId));return alias?.id||rawProjectId}
function addImportedProjectSnapshot(snapshot){if(!snapshot?.id)return false;const existing=projectById(snapshot.id);if(!existing&&!WORKSPACE_LOCAL.importedProjects.some(project=>project.id===snapshot.id)){WORKSPACE_LOCAL.importedProjects.push(snapshot);return true}return false}
